import re

# Read the index.html file
with open('index.html', 'r') as f:
    content = f.read()
    lines = content.split('\n')

print(f"Found DEL- prefix at line 1242")
print(f"Current line: {lines[1241].strip()}")

# Fix the specific line - remove the id field entirely
# The backend should generate the ID
lines[1241] = lines[1241].replace("id: `DEL-${Date.now()}`,", "// id will be generated by Firestore")

# Join the lines back
content = '\n'.join(lines)

# Also check if there's a pattern where we're using newDelivery.id
# and make sure we use the response.data instead
content = re.sub(
    r'setDeliveries\(prev => \[\.\.\. ?prev, \{ \.\.\. ?newDelivery, id: response\.data\.id \}\]\)',
    'setDeliveries(prev => [...prev, response.data])',
    content
)

# Write the fixed content
with open('index.html', 'w') as f:
    f.write(content)

print("\n✅ Fixed delivery ID generation!")
print("Changes made:")
print("1. Removed id: `DEL-${Date.now()}` from line 1242")
print("2. Backend will now generate the ID")
print("3. Using response.data for state updates")
