name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: List directory structure
      run: |
        echo "Root directory:"
        ls -la
        echo -e "\nFrontend directory:"
        ls -la frontend/
        echo -e "\nFrontend/public directory:"
        ls -la frontend/public/
        
    - name: Verify index.html exists
      run: |
        if [ -f frontend/public/index.html ]; then
          echo "✅ index.html found"
          echo "File size: $(ls -lh frontend/public/index.html | awk '{print $5}')"
        else
          echo "❌ index.html NOT FOUND"
          exit 1
        fi
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './frontend/public'
        
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
